version: '3'
services:
  rest:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'backend'
    environment:
          SPRING_DATASOURCE_URL: jdbc:mysql://sql8.freesqldatabase.com:3306/sql8629573
          SPRING_DATASOURCE_USERNAME: ${USER}
          SPRING_DATASOURCE_PASSWORD: ${PASSWORD}
    ports:
      - "8081:8081"

  react:
    build:
      context: src/main/webapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    image: 'frontend'
    depends_on:
      - rest

