version: '3'
services:
  rest:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'backend'
    environment:
          SPRING_DATASOURCE_URL: jdbc:mysql://db4free.net:3306/postmanager_db
          SPRING_DATASOURCE_USERNAME: postmanager_data
          SPRING_DATASOURCE_PASSWORD: ads778899
    ports:
      - "8082:8082"

  react:
    build:
      context: src/main/webapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    image: 'frontend'
    depends_on:
      - rest

